name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0' # Specify the desired Flutter version

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # Uncomment this step to verify formatting
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

#       Uncomment this step if you want to build the project
      - name: Build APK
        run: flutter build apk --release
